### ISSUE TITLE
CW Reports - Citistat report

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Cityworks_Reporting#11]
Please see the report attached in email from 5/22:

The report that I’ve attached is still in draft format, but Amy wants to see it for the following:

“ It should include the Water work orders that have been processed since we went live with water April 16.  Can it be run for the period April 26 through May 9?  That corresponds to the last Citistat report that was generated from the CSR system.”

She speaks about the 16th in the first sentence, then the 26th in the next – can you run it twice, once as described, and once from the 16th?

**Comment by BC89** [comment]
Can you please send this email again. Is this the report that Amy stated was urgent and that Bharat would provide specifications for? I haven’t received anything more since.

**Comment by JMurk** [comment]
Closing this... no longer relevant.
