### ISSUE TITLE
CW Reports - List of Work Report - Limit Status Options

### ISSUE THREAD

**Issue by JMurk** [JMurk/Cityworks_Reporting#2]
Issue:  The current list of options for the Status parameter has too many options.

Resolution:  Please limit the list of options on the Status parameter to NEW, OPEN, and COMPLETE

**Comment by mohsinkar** [comment]
Status parameter updated

**Comment by JMurk** [comment]
Will test when moved to CW.

**Comment by JMurk** [comment]
Confirmed complete.
