### ISSUE TITLE
CW Reports -  List of Work - Not Returning Any Results

### ISSUE THREAD

**Issue by JMurk** [JMurk/Cityworks_Reporting#22]
Issue:  No matter the parameter combination, I can not get this report to produce any results.

**Comment by JMurk** [comment]
Found the issue:  The O-New option is incorrect.  It should be O-NEW.  Please update.

**Comment by mohsinkar** [comment]
Update to O-NEW

**Comment by JMurk** [comment]
Confirmed complete.
