### ISSUE TITLE
Report - Main Chokes with No CCTV 

### ISSUE THREAD

**Issue by JMurk** [JMurk/Cityworks_Reporting#26]
A new auto-emailed report is needed.  Here are the specifics:

**Source:**  DPW_CityworksReporting.V_MAINCHOKES_NOCCTV (Select all)
**Timing:**  Every Monday 9AM
**Recipients:**  TBD - send dev to joe.murk@baltimorecity.gov and alan.foster@baltimorecity.gov

**Comment by JMurk** [comment]
Confirmed in dev.  Please push to prod with the email addressed to:

Alan.foster
David.thompson
Stephen.lampo
Eric.ritter

All @ baltimorecity.gov

**Comment by jday3** [comment]
done. just sent out the first one, so let me know if anyone didn't get it. It will be sent on Mondays at 9 from now on

**Comment by JMurk** [comment]
Confirmed complete.

**Comment by alanfoster99** [comment]
Joe, can you add Address to the fields?

**Comment by JMurk** [comment]
Should be in tomorrow's list.  Close this when you can confirm.

**Comment by alanfoster99** [comment]
Checked this morning's weekly report -- it does not include address.

http://dpwview.baltimorecity.gov/water/Portal/Reports/MainChokesNoCCTV/MainChokesNoCCTV12142015_0900AM.xlsx

**Comment by JMurk** [comment]
My fault, should be on the next one.

**Comment by JMurk** [comment]
Jesse, do you have to do something on your end to include address?  I have added it to the view.

**Comment by jday3** [comment]
Yes, the reports are generated in code, so any change to the report needs to be done there.

**Comment by jday3** [comment]
The report generation was updated. Let me know if you want me to run the report again instead of waiting until next monday.

**Comment by alanfoster99** [comment]
Confirmed and closing
