### ISSUE TITLE
CW Reports - CitiStat Report - Percentages 

### ISSUE THREAD

**Issue by JMurk** [JMurk/Cityworks_Reporting#6]
Please add % for percent fields (e.g. 9.06 %).
![image](https://cloud.githubusercontent.com/assets/5805454/2779001/2ed0b67e-caf8-11e3-94f2-db455aafa4b0.png)

**Comment by JMurk** [comment]
Confirmed complete- Question:  Is it possible to hide decimals when they are .00?

**Comment by JMurk** [comment]
Please answer the question above.

**Comment by mohsinkar** [comment]
No, tried this but no success.

**Comment by JMurk** [comment]
Ok, thanks for the response.  Closing.
